# Generated by Django 6.0.7 on 2026-08-01 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('staff_role_label', models.CharField(editable=False, help_text='Denormalized display label. Source of truth is role.', max_length=100)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('joining_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='rbac.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='tenants.tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['tenant'], name='staff_staff_tenant__b387e6_idx'), models.Index(fields=['role'], name='staff_staff_role_id_d32aeb_idx'), models.Index(fields=['employment_status'], name='staff_staff_employm_0af27c_idx')],
            },
        ),
    ]
