# Generated by Django 6.0.7 on 2026-08-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='photo',
            new_name='photo_url',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_role_label',
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='rbac.role'),
        ),
    ]
