# Generated by Django 6.0.7 on 2026-08-16 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_type', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('student', 'Student')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('stripe_line_item_id', models.CharField(max_length=255)),
                ('purchased_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_addons', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
