# Generated by Django 6.0.7 on 2026-07-26 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=255)),
                ('subdomain_slug', models.SlugField(max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('ultra', 'Ultra')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('admin_license_limit', models.PositiveIntegerField()),
                ('faculty_license_limit', models.PositiveIntegerField()),
                ('staff_license_limit', models.PositiveIntegerField()),
                ('student_license_limit', models.PositiveIntegerField()),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['school_name'],
            },
        ),
    ]
