# Generated by Django 6.0.7 on 2026-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterModelTable(
            name='academicsession',
            table=None,
        ),
        migrations.AlterModelTable(
            name='classlevel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='section',
            table=None,
        ),
    ]
