# Generated by Django 6.0.7 on 2026-08-09 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0002_alter_academicsession_created_at_and_more'),
        ('academics', '0002_timetableperiod'),
        ('staff', '0002_rename_photo_staff_photo_url_and_more'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academic_structure.academicsession')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance_records', to='staff.staff')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academics.timetableperiod')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academic_structure.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['date', 'student__student_code'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date', 'period'), name='uq_attendance_student_date_period')],
            },
        ),
    ]
