# Generated by Django 6.0.7 on 2026-08-01 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_admin_role', models.BooleanField(default=False, help_text='Admin roles bypass role permissions entirely and always have full access.')),
                ('license_category', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('cloned_from_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_roles', to='rbac.role')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('students', 'Students'), ('attendance', 'Attendance'), ('academics', 'Academics'), ('grades', 'Grades'), ('fees', 'Fees'), ('messages', 'Messages'), ('staff', 'Staff'), ('calendar', 'Calendar'), ('library', 'Library'), ('transport', 'Transport'), ('admissions', 'Admissions'), ('documents', 'Documents'), ('cafeteria', 'Cafeteria'), ('health', 'Health'), ('alumni', 'Alumni')], max_length=30)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('allowed', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.role')),
            ],
            options={
                'ordering': ['module', 'action'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'module', 'action'), name='unique_role_permission'),
        ),
    ]
