# Generated by Django 6.0.7 on 2026-08-02 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0002_alter_academicsession_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=100)),
                ('file_url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'applicant_document',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('applied', 'Applied'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='inquiry', max_length=20)),
                ('entrance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applying_for_class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='academic_structure.classlevel')),
            ],
            options={
                'db_table': 'applicant',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
