# Generated by Django 6.0.7 on 2026-08-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='linked_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['tenant'], name='applicant_tenant__af5e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='applicant_status_fbd0d5_idx'),
        ),
    ]
