# Generated by Django 6.0.7 on 2026-08-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_applicant_linked_student'),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="gender",
            field=models.CharField(
                max_length=10,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                ],
                default="male",
            ),
            preserve_default=False,
        ),
    ]
